version: 2 # use CircleCI 2.0
orbs:
  allure: ayte/allure@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: npm install # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test --reporters=allure --maxInstances=1 # replace with `yarn test` if using yarn

      - run:
          name: Generate report
          # command: allure generate
          command: npm run report:generate

      - allure/report

      - store_artifacts: 
          path: ./allure-report

      - store_test_results:
          path: test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - build